### PR TITLE
Add Vercel routes for public write API

### PR DESCRIPTION
**Pull request by mqp**
Now you can `POST /api/v0/markets` to create a market and `POST /api/v0/bets` to make a bet. These routes will just forward your request to the relevant cloud function and do zero intelligent work on their own.

### CODE REVIEW

**Comment by akrolsmir** [comment]
This looks super, super cool! I'm going to ask @sipec to be the main reviewer on this, so that we spread out knowledge on how the API works a bit more.

Also, could you document how the write API will work? For this PR, just the parameters etc that will be used to create/bet on markets. Later ofc we'll want to publish a full "how to use the Manifold Write API" documentation (eg where to get token, how to form requests, ideally code snippets you can run in Javascript and Python)

**Comment by mqp** [comment]
> Also, could you document how the write API will work? For this PR, just the parameters etc that will be used to create/bet on markets. Later ofc we'll want to publish a full "how to use the Manifold Write API" documentation (eg where to get token, how to form requests, ideally code snippets you can run in Javascript and Python)

Of course, I am just working through it gradually. Currently I feel that all the "general API machinery" is good to go, so next I want to revisit the specific parameters and outputs of our existing APIs to make sure they make sense, and then I will write documentation and we can announce it.

**Comment by mqp** [comment]
@sipec any comment?

**Review by sipec — APPROVED** [review]
This looks pretty good!
(Thanks for being patient 😅 )

**Pull request merged**
