### PR TITLE
Make `onCreateCommentOnContract` trigger more efficient

### PR DESCRIPTION
**Pull request by mqp**
Like #1187, I am not sure if this is super important, but if I want to find something missing, and it's hard to find, I start cleaning my house and see if it turns up.

### CODE REVIEW

**Comment by jahooma** [comment]
Sorry, I told @IanPhilips about this and he made his own improvements, so you'll have to merge.

I think though that you might have found different things to optimize than him.

**Review by jahooma — APPROVED** [review]
Thanks Marshall. LGTM!

**Review by IanPhilips — APPROVED** [review]
LGTM! In my other commit 6516bae I opted for reducing the computation needed to calculate investment value of bets at the expense of 'with shares in' being more of a educated guess than a certainty

**Comment by IanPhilips** [comment]
Oh it looks like it's still timing out. Hmmmm I might just increase the timeout 
Screen Shot 2022-11-16 at 8 26 21 AM

**Comment by IanPhilips** [comment]
I made a couple more adjustments: lengthening the timeout, adding logs each step of the way, and using the uniqueBettorIds field rather than finding the unique bettors. On that topic though, the popular contracts are now carrying around 1500 strings with them. Perhaps it's time to move those unique bettor ids to a subcollection...

**Comment by IanPhilips** [comment]
Looks like we're in the clear!
Screen Shot 2022-11-16 at 9 28 42 AM

**Comment by jahooma** [comment]
> Looks like we're in the clear! A new comment on dan-stock from memestiny finished in under 20 seconds (1600 traders) screenshot removed b/c it included emails

Thanks @IanPhilips!

**Pull request merged**
