### PR TITLE
WIP: mobile betting in embeds

### PR DESCRIPTION
**Pull request by mantikoros**

### CODE REVIEW

**Comment by mantikoros** [comment]
It seemed like a good idea, but the betting interface takes up too much room in the embeds, I think. 
Screen Shot 2022-09-30 at 8 05 22 PM
Screen Shot 2022-09-30 at 8 05 32 PM

**Comment by ingawei** [comment]
> It seemed like a good idea, but the betting interface takes up too much room in the embeds, I think. Screen Shot 2022-09-30 at 8 05 22 PM Screen Shot 2022-09-30 at 8 05 32 PM

Yeah I also feel like maybe having anything expand out in embeds may be a bad idea?

**Comment by mantikoros** [comment]
> Do you want to just wait until I push embed design changes before making these?

Yeah, whatever design you propose is probably better. I'll just close this PR.

**Comment by ingawei** [comment]
Sorry! Hope you didn't spend too much time on it :(

**Pull request closed without merging**
