### PR TITLE
[WEB] Select Answer in Positions If Many Answers

### PR DESCRIPTION
**Pull request by casesandberg**
If more than 4 answers on multiple choice, hide carousel and use select instead. 

Screenshot 2024-01-25 at 10 58 46 PM

### CODE REVIEW

**Comment by jahooma** [comment]
Nice, looks good, and sorely needed!

**Comment by IanPhilips** [comment]
Thanks for working on this, it's pretty unusable atm! Just one problem with the UI as you have it now, on mobile it's wider than the page:
Screenshot 2024-01-29 at 10 13 16 AM

**Comment by casesandberg** [comment]
@IanPhilips My bad, just pushed a fix for that overflow issue

**Comment by IanPhilips** [comment]
Looks great, thanks @casesandberg!

**Pull request merged**
