### PR TITLE
Updated displaying for fine managrams

### PR DESCRIPTION
**Pull request by ProgramCrafter**
Fixes
изображение

### CODE REVIEW

**Comment by IanPhilips** [comment]
Hey thanks for this! I'd love it if it didn't say that Ian Philips paid Relay, though. Perhaps you can move fine to replace the paid bit?
Screenshot 2023-09-21 at 9 10 28 AM

**Comment by ProgramCrafter** [comment]
Done! It should display things correctly now.
```
[A's perspective]
A paid B -M1000
A fined B +M1000

[B's perspective]
A paid B +M1000
A fined B -M1000
```

**Comment by IanPhilips** [comment]
Almost there! There is still one more case to handle 😅. I tried fining someone on dev for you but the dev api won't recognize me as an admin after deploying a couple times...
Screenshot 2023-09-21 at 10 19 33 AM
Screenshot 2023-09-21 at 10 19 16 AM

**Comment by ProgramCrafter** [comment]
> I tried fining someone on dev for you but the dev api won't recognize me as an admin after deploying a couple times...

That's probably because my pull request hasn't yet merged the change 8df24eb where you were added to dev admins?

26813c0 fixes +- and -- signs.

**Comment by IanPhilips** [comment]
I was trying on dev.manifold.markets! But a good thought. Will check it out in a sec

**Comment by IanPhilips** [comment]
Looks great, thanks!

**Pull request merged**
