### PR TITLE
Ingawei/cleanup repost

### PR DESCRIPTION
**Pull request by ingawei**
Updated the look of reposts to be more consistent with the rest of the feed
image
image

Not sure if I saw all the cases since I was just scrolling through the feed to see if everything looked normal, would appreciate a look

### CODE REVIEW

**Comment by IanPhilips** [comment]
Cool! Will take a look, is moving the three dot menu down intentional here? It looks a bit weird to be not top-right aligned with the content.
Screenshot 2024-07-10 at 11 52 43 AM

**Comment by ingawei** [comment]
> Cool! Will take a look, is moving the three dot menu down intentional here? It looks a bit weird to be not top-right aligned with the content. Screenshot 2024-07-10 at 11 52 43 AM

**Comment by ingawei** [comment]
> Cool! Will take a look, is moving the three dot menu down intentional here? It looks a bit weird to be not top-right aligned with the content. Screenshot 2024-07-10 at 11 52 43 AM

oops no you're right, that was unintentional

**Comment by ingawei** [comment]
> > Cool! Will take a look, is moving the three dot menu down intentional here? It looks a bit weird to be not top-right aligned with the content. Screenshot 2024-07-10 at 11 52 43 AM
> 
> oops no you're right, that was unintentional

pushed a fix

**Review by IanPhilips — APPROVED** [review]
Looks good! I don't see any obvious errors and the logic is a bit tricky to get right so I say we just review in prod.

**Pull request merged**
