### PR TITLE
add Cavendish Labs

### PR DESCRIPTION
**Pull request by ag8**

### CODE REVIEW

**Review by akrolsmir — COMMENTED** [review]
Hey @ag8! The code looks good, thanks for submitting this.

The only hangup is that I don't see a way for us to actually send money to Cavendish Labs. We're happy to send money to any 501c3, but we'd need some method of actually doing so (usually, credit card purchase, Venmo or Paypal are ways that we've set up before). Do you happen to know how we could forward donations to Cavendish (are you affiliated with them?)

**Comment by jmcavanagh** [comment]
Does Wise work? @akrolsmir

**Comment by akrolsmir** [comment]
> Does Wise work? @akrolsmir

I don't believe we have Wise set up to send payments, unfortunately...

**Comment by jmcavanagh** [comment]
That's OK. I've created a paypal for us. The link to donate is https://www.paypal.com/donate/?hosted_button_id=ZMCEJNMYXEXFE

**Pull request merged**
