### PR TITLE
Dream UI update

### PR DESCRIPTION
**Pull request by chitalian**
Notes: 
Please do not review the code - it is something I just hacked together for the demo.

I am hoping to just review the basic product flow and get design feedback first.

Loom:
https://www.loom.com/share/dd88b5f667324b04aadaf1e957319bbb

### CODE REVIEW

**Comment by IanPhilips** [comment]
Hey this looks cool!!

**Comment by IanPhilips** [comment]
Lol that koala was pretty decidedly un-picasso like.

**Review by sipec — COMMENTED** [review]
I like the UI. I think it makes sense and is intuitive

**Comment by sipec** [comment]
alas technology marches on

**Pull request closed without merging**
