### PR TITLE
Swap values with structured assignment rather than temporary

### PR DESCRIPTION
**Pull request by Sjlver**
Saves two lines and a variable.

Also, a desperate attempt to save my Mana in https://manifold.markets/ManifoldMarkets/if-we-open-source-our-frontend-code

### CODE REVIEW

**Comment by akrolsmir** [comment]
Hrm, seems to have generated a typescript build error of some kind kind here?

I appreciate the attempt at market manipulation! I'd probably lump together your 4 outgoing PRs as a single "significant contribution" for the purposes of the market 😝

(though - small PRs are great, thanks for splitting these up)

**Comment by mqp** [comment]
You need a semicolon because the second line is otherwise ambiguous between a new statement and an indexing expression.

**Comment by Sjlver** [comment]
Thanks for finding the semicolon problem. Fixed now.

Note: for some reason, `prettier` wants the semicolon to go to the beginning of the line.

> I appreciate the attempt at market manipulation! I'd probably lump together your 4 outgoing PRs as a single "significant contribution" for the purposes of the market 😝

Fair enough ;-)

**Comment by jahooma** [comment]
This code is not an improvement. Pull requests like this also cost attention.

Despite the good intentions, I don't think this PR should have been merged in.

**Pull request merged**
