### PR TITLE
condense comment logic in one component

### PR DESCRIPTION
**Pull request by IanPhilips**
this reduces comment input logic complexity, only one component handles comment logic now.

### CODE REVIEW

**Review by jahooma — APPROVED** [review]
Nice, I like the simplification!

I also wonder whether we should move to only showing your position and not your recent bet amount...

**Comment by IanPhilips** [comment]
This allows your written comment to persist on to a bet so you don't have to rewrite it if you wrote a comment, then bet, then wanted to add that comment on to the bet.

**Comment by IanPhilips** [comment]
Hmmm I personally like to highlight that my recent position has changed when I attach it to a bet

**Comment by jahooma** [comment]
> Hmmm I personally like to highlight that my recent position has changed when I attach it to a bet

Good point! Maybe it should always show your current position, but in this case show the diff? Something to think about.

**Pull request merged**
