### PR TITLE
add bets and user tables per market

### PR DESCRIPTION
**Pull request by Gurkenglas**
So it turns out you can add a bets table that lets the user sort and filter using like one line. Then I added some more lines for formating and styling and another table of each user's position. Feel free to redo any or all of it or give feedback.
Screenshot from 2022-08-09 02-50-05
Screenshot from 2022-08-09 02-50-13

### CODE REVIEW

**Comment by Gurkenglas** [comment]
Note that this, uh, pays no attention to whether a bet is too old to have its owner named.

**Comment by sipec** [comment]
I love the concept / implementation. I think a table display of bets and users that have bet is very useful.

I think it's worth it for me to take over the design work on this and finish it up, but probably not this week :/

**Comment by Gurkenglas** [comment]
Eh, I can just use vercel's deployment, it's everyone else's loss if they don't have such tables. Except that annoyingly I can't log in through it.

**Comment by jahooma** [comment]
Added the vercel deployment to the authorized domain whitelist, so you should be able to login now

**Comment by gappleto97** [comment]
Here's a market for this:  https://manifold.markets/MarketManagerBot/how-many-days-after-september-1st-w-77e92d9620d1

**Pull request closed without merging**
