### PR TITLE
Add rewrite rule to redirect to new api

### PR DESCRIPTION
**Pull request by jahooma**

### CODE REVIEW

**Comment by mqp** [comment]
Please explain - what is the motivation? Is this different than the existing approach? Does it pass through an `X-Forwarded-For` IP correctly?

**Comment by jahooma** [comment]
I think we don't get charged for execution time of the middleware. That's all.

> Does it pass through an X-Forwarded-For IP correctly?
I have no idea 😂

**Comment by mqp** [comment]
Then please don't merge this until you have verified that the Google Cloud rate limiting will work with requests passed through this system. If all Vercel users were collectively limited to 1000 req/min because GCP wasn't able to distinguish between them, that would break people's existing integrations.

**Comment by jahooma** [comment]
This might work, but would need to managed by someone who understands the google cloud rate limiting rules.

**Pull request closed without merging**
