### PR TITLE
restyle home page (separation between markets)

### PR DESCRIPTION
**Pull request by sipec**
Replace ugly line with:

image

### CODE REVIEW

**Review by akrolsmir — APPROVED** [review]
Eh I didn't hate the old version (but I'm biased, I implemented it). Wondering - maybe we just wanted to use `divide-gray-50` instead of `divide-gray-300` and then it looks good?

Anyways, this version looks fine too!

**Comment by mantikoros** [comment]
I think just making the line lighter would look best.

**Comment by jahooma** [comment]
I like the gap better. Was never much a fan of the border line. It's also what Facebook does.

**Comment by sipec** [comment]
I now see the wisdom of pushing to main directly - prevents bikeshedding

side note: probably the "your trades" page should also follow the same style

**Pull request merged**
