### PR TITLE
[API] Add Leagues

### PR DESCRIPTION
**Pull request by casesandberg**

### CODE REVIEW

**Review by jahooma — APPROVED** [review]
LGTM! Thanks Case!

**Comment by jahooma** [comment]
I'll let @sinclairity also review it

**Comment by sipec** [comment]
I'm going to change this to not require the userId

**Comment by sipec** [comment]
also idk about including the `rankSnapshot` and `Primary Key` in the results

**Comment by casesandberg** [comment]
It would be good to know what place you got in the league (I believe thats rank snapshot right?). `Primary key` is not needed.

**Comment by sipec** [comment]
nvm I am dum. I just thought it was always null (but I guess that just means unranked?)

**Pull request merged**
