### PR TITLE
Show spent mana in positions tab

### PR DESCRIPTION
**Pull request by Bohaska**
This shows the `invested` amount of each user under their shares/profit in the positions tab

### CODE REVIEW

**Comment by Bohaska** [comment]
here's what it looks like

image

**Comment by Bohaska** [comment]
looks like this at phone dimensions image

**Comment by jahooma** [comment]
This is great information to show.

However, it looks pretty busy, especially on mobile. I'm not sure if it makes sense to be in the same column as Max payout.

This was a difficult screen for users to figure out already.

Maybe remove it on mobile (`hidden sm:flex`) and I'll merge it to get feedback.

**Comment by Bohaska** [comment]
> This is great information to show.
> 
> However, it looks pretty busy, especially on mobile. I'm not sure if it makes sense to be in the same column as Max payout.
> 
> This was a difficult screen for users to figure out already.
> 
> Maybe remove it on mobile (`hidden sm:flex`) and I'll merge it to get feedback.

Done!

**Pull request merged**
