### PR TITLE
[API] Expose Leagues Endpoint

### PR DESCRIPTION
**Pull request by casesandberg**
I forgot to expose the api as an endpoint...

### CODE REVIEW

**Comment by jahooma** [comment]
I think it's ok to only expose on the new api URL. Everyone should start using that instead
@sinclairity

**Comment by jahooma** [comment]
My understanding is that this should URL work once we redeploy (doing that now...):

https://api.manifold.markets/leagues?userId=5LZ4LgYuySdL1huCWe7bti02ghx2

**Comment by casesandberg** [comment]
OH! Got it, thats easy. Should I build all my stuff using this new endpoint then?

**Comment by jahooma** [comment]
I guess not everything is migrated over yet, but most of the getters are, like /bets and /markets, which you could start using, yes!

**Pull request closed without merging**
