### PR TITLE
Update constants.ts

### PR DESCRIPTION
**Pull request by tspoerri**
Make @oh trustworthy? 😇

### CODE REVIEW

**Comment by IanPhilips** [comment]
Closing for now until we've better info.

**Comment by tspoerri** [comment]
I’m so sorry, it didn’t occur to me that the PR would be misleading/disruptive for admins with whom I didn’t discuss this! I’ve made my case to a number of you, with noncommittal positive responses, but no, it has not been approved.

**Comment by tspoerri** [comment]
@IanPhilips (See above)

**Comment by IanPhilips** [comment]
Ah okay, no hard feelings! I'll ask in the discord and see what they say, then. Will report back soon!

**Comment by IanPhilips** [comment]
https://discord.com/channels/915138780216823849/1158528733444055071/1169492110106443887

**Comment by tspoerri** [comment]
@IanPhilips That was… interesting. Now what? 😁
DFFE134E-410C-45D2-80A1-1FD2533C13D4

**Pull request closed without merging**
