### PR TITLE
Add basic market to filtering tiers

### PR DESCRIPTION
**Pull request by Bohaska**
common complaint

### CODE REVIEW

**Comment by IanPhilips** [comment]
You can check it out at the Visit Preview button! 
Screenshot 2024-09-18 at 10 03 50 PM

It looks like when I hit the basic tier, there's a weird little nub of a pill that appears highlighted.
Screenshot 2024-09-18 at 10 03 31 PM

**Comment by Bohaska** [comment]
Oh, it's because I didn't set an icon for Basic markets 😅 

I'll go check it tomorrow

**Comment by Bohaska** [comment]
lol did it take me that long to realize that was the error

**Comment by Bohaska** [comment]
I'm going to close this when I'm done testing on the dev server and make a new PR without so many commits on it

**Comment by Bohaska** [comment]
yay it finally works!

**Pull request closed without merging**
