### PR TITLE
Switch to SF Compact as default font

### PR DESCRIPTION
**Pull request by mantikoros**

### CODE REVIEW

**Comment by jahooma** [comment]
Cool!

You should post a screenshot with any PR with visual changes.

**Comment by akrolsmir** [comment]
Yeah definitely not a fan, but I guess I could be wrong. As usual, would suggest setting up a FR prediction market to see what users think.

**Comment by mqp** [comment]
I agree that I think I prefer the status quo, although I'm not married to the current font and I think someone could find a new one with new weights that I liked a lot better.

**Comment by mantikoros** [comment]
I feel stronger that the current font is bad, than that my current choice is good.

**Comment by sipec** [comment]
I like our current font. It's fun

**Pull request closed without merging**
